### ISSUE TITLE
Allow configurable 'origin' url

### ISSUE THREAD

**Issue by spuder** [blakawk/gitlab-integration#15]
It would be nice if the 'origin' url was configurable. 
I have many repos where I have more than one remote. For clarity I make the 'origin' more specific.

e.g.

```bash
git remote -v
gitlab	git@gitlab.example.com:foo/bar.git (fetch)
gitlab	git@gitlab.example.com:foo/bar.git (push)
github	git@github.com:foo/bar.git (fetch)
github	git@github.com:foo/bar.git (push)
```

My work around is to rename the origin on all git repos

    git remote rename gitlab origin

**Comment by blakawk** [comment]
Currently, the plug-in is not reading any particular git remote but makes
use of atom GitRepository API getOriginUrl :
https://atom.io/docs/api/latest/GitRepository#instance-getOriginURL

Trying to allow the user to specify a particular remote will require to
parse git  repository configuration, which I wanted to avoid.

Even if I wanted to allow the user to specify a particular remote name to
retrieve gitlab project URL, this URL would be common for all projects
loaded in the atom instance, which I wanted to avoid by trying auto
detecting it. If I do implement this, how can I let the user specify which
remote to use ? For me, naming the remote "origin" seemed sufficient,
what's your opinion ?

**Comment by spuder** [comment]
I didn't think about the fact that it is global for all git repos. Because of that making it configurable doesn't make sense.
