### ISSUE TITLE
Breaks if group name is case sensitive

### ISSUE THREAD

**Issue by meatherly** [blakawk/gitlab-integration#26]
I was noticing for awhile that my loading icon continues to show and I didn't know why so I did some debugging and noticed if the group-name for the repo is case sensitive then plugin breaks. 

I've created a test repo to prove this: https://gitlab.com/CaseSentiveGroup/express-app-test

I might have a fix soon that I can push up. This is the first time working on a atom package so I might need some help :p 

Let me know if you need access to the group to test this bug out. 

Just to be clear it's getting all the information about the jobs and pipelines but it can't find the project because the project look up isn't working because of casing.

**Comment by Stieneee** [comment]
@meatherly I had the same problem with some case-sensitive projects. I attempted a fix. Feel free to try and comment. First time working with an atom package/coffee script.

**Comment by blakawk** [comment]
@Stieneee thanks for your contribution I'll review it soon.
