### ISSUE TITLE
no GitLab project detected when GitLab EE is used

### ISSUE THREAD

**Issue by BreatheDigital** [blakawk/gitlab-integration#35]
Pipeline status is not shown on ATOM statusbar, when git repo hosted on GitLab Enterprise (EE) is used as origin.

**no GitLab project detected in xxx/yyy**

It seems like it is always trying to default it to https://www.gitlab.com/xxx/yyy instead of https://<any custom gitlab EE URL>/xxx/yyy

Is there a way to pass on the GitLab EE hostname in the place of www.gitlab.com, because technically /api/v4 APIs are similar between GitLab CE and EE. It would be a welcome addition to support GitlabEE..

TIA!
~rg

**Comment by blakawk** [comment]
@BreatheDigital can you please enable package debug output and provide Atom console output ?
Or at least, can you give the output of command `git remote show origin` in the root of your project in a terminal ? Thanks.

**Comment by BreatheDigital** [comment]
Enabled package debug output, still no logs shown in DevTools->Console for your package files (status-bar-view.coffee or gitlab-integration.coffee).

> **git remote show origin** returns:
`* remote origin  `
`Fetch URL: git@my.company.host:group-name/repo-name.git`
`Push  URL: git@my.company.host:group-name/repo-name.git`
`HEAD branch: master`
`Remote branches:`
    `master  tracked`  
    `patch-1 tracked`
    `patch-2 tracked`
`Local branch configured for 'git pull':` 
    `master merges with remote master`  
`Local ref configured for 'git push': ` 
`    master pushes to master (fast-forwardable)`

**Comment by blakawk** [comment]
You need to filter log.coffee

**Comment by BreatheDigital** [comment]
nothing comes by in the filters. I see that gitlab-integration is enabled, and, can see Question Mark with the label **no GitLab project detected in xxx/yyy** after every PUSH / pipeline trigger.

**Comment by blakawk** [comment]
can you show me a screenshot ? There is no difference between gitlab EE & CE indeed, and the plugin is not using any hardcoded value regarding the host to which the API is retrieven. Does your gitlab EE is listening on HTTP(s) defaults ports (80 for HTTP, 443 if HTTPS) ? Is your gitlab server SSL certificate is correctly recognized by your browser as safe ?

**Comment by BreatheDigital** [comment]
Dear @blakawk - Thanks for your prompt suggestions. I was able to resolve the issue, by reinstalling ATOM latest portable pack. It could be that my system proxy settings are not helping for your plugin to reach Git instance. Anyways, it's history now. It's working! Thanks once again and great job with this plugin! :)

**Comment by blakawk** [comment]
Well that's good news I'm happy to hear it 😌
Have a nice day and enjoy then !

Le mer. 29 août 2018 à 22:18, BreatheDigital <notifications@github.com> a
écrit :
