### ISSUE TITLE
gitlab-integration doesn't recognize git clone through ssh 

### ISSUE THREAD

**Issue by rdwrt** [blakawk/gitlab-integration#36]
When cloning from ssh gitlab-integration doesn't recognize the repo as a gitlab repo. 
Moving to https clone works. 
A helpful error message would already be an improvement.

**Comment by blakawk** [comment]
Cloning from SSH should work only if the gitlab server is accessible through standard HTTPS port (ie 443) at the same address used to clone the repo. Can you provide more information on why it is not working in your case ? Like plugin's debug output in Atom developper console (after enabling it in plugin's settings). Thanks.
