### ISSUE TITLE
Self-Hosted GitLab

### ISSUE THREAD

**Issue by ZerkerEOD** [blakawk/gitlab-integration#38]
Is there a way to get this to work with self-hosted gitlab?

**Comment by blakawk** [comment]
Yes it should work on self-hosted gitlab out of the box. In case you use HTTPS to connect to Gitlab, you might need to disable SSL certificate checking in plugin's settings:

![image](https://user-images.githubusercontent.com/1149069/49718977-14be3280-fc5c-11e8-8ceb-817b93191c12.png)

**Comment by ZerkerEOD** [comment]
I see the settings say to make sure the url is correct but I can't get anywhere to clone my repository or add a remote unless I am using github.

**Comment by blakawk** [comment]
You need to clone your repository using command line in a terminal. What platform are you on (windows or linux) ? Just follow your Gitlab Project Help in cloning your repository ;)
