### ISSUE TITLE
Issue using HTTPS

### ISSUE THREAD

**Issue by dhope0000** [blakawk/gitlab-integration#5]
Installed the package

Set it up as per instructions

git remote show origin looks like 

```
$ git remote show origin
* remote origin
  Fetch URL: https://My-gitlab-Address/repository/SomeRepo.git
  Push  URL: https://My-gitlab-Address/repository/SomeRepo.git
  HEAD branch: master
  Remote branches:
      # loads of branches
  Local branch configured for 'git pull':
    master merges with remote master
  Local ref configured for 'git push':
    master pushes to master (up to date)
```

**Comment by dhope0000** [comment]
On Ubuntu this returns "no project found"

**Comment by blakawk** [comment]
@dhope0000 can you enable debug output in package settings and post console content with v0.2.7 ? Thanks !

**Comment by blakawk** [comment]
@dhope0000 any news on the debug output ? Thanks !

**Comment by dhope0000** [comment]
Hey i think this was an issue with my connection more than the plugin as its been working over the last couple of days, ill comment again if I can get it to happen again!

**Comment by simonspa** [comment]
I have the same problem with my repo URL looking like this:
```
$ git remote -v 
origin	ssh://git@gitlab.myserver.com:7999/myuser/myproject.git (fetch)
origin	ssh://git@gitlab.myserver.com:7999/myuser/myproject.git (push)

```
The console gives me:
```
cannot fetch projects from gitlab.myserver.com:7999 
FetchErrorcode: "EPROTO"
errno: "EPROTO"
message: "request to https://gitlab.myserver.com:7999/api/v4/projects?membership=yes failed, 
reason: write EPROTO 140020043348672:error:140770FC:SSL 
routines:SSL23_GET_SERVER_HELLO:unknown protocol:../../vendor/node/deps/openssl/openssl/ssl/s23_clnt.c:794:
"name: "FetchError"stack: (...)get stack: stack()
arguments: 
nullcaller: 
nulllength: 0
name: "get stack"__proto__: ()
apply: apply()
arguments: (...)get 
arguments: ThrowTypeError()set 
arguments: ThrowTypeError()
bind: bind()
call: call()
caller: (...)get 
caller: ThrowTypeError()set 
caller: ThrowTypeError()
constructor: Function()
length: 0
name: ""toString: toString()Symbol(Symbol.hasInstance): [Symbol.hasInstance]()__proto__: Object<function scope><function scope>set 
stack: stack()
arguments: null
caller: null
length: 1
name: "set stack"__proto__: ()<function scope>type: "system"__proto__: Errorconstructor: FetchError(message, type, systemError)__proto__: Object
```
The server runs Gitlab v9.3

**Comment by dhope0000** [comment]
Are you using a self signed certificate?

**Comment by simonspa** [comment]
Hi @dhope0000 
nope, the certificate is signed by Comodo and accepted as valid by all major browsers.

**Comment by blakawk** [comment]
@simonspa this is because you are using non-standard port in your connection information. `gitlab-integration` is using your origin to retrieve the associated port, and uses it to connect through HTTPS. However, in your case, on port 7999 retrieved from your project's origin, you must have a SSH server listening, and the gitlab API should be accessible on HTTPS on another port, for which there is no mean to know which one.

You should either use default ports in your gitlab configuration, or use an HTTPS origin using the non-standard port you configured.

**Comment by simonspa** [comment]
@blakawk hm, okay, but that requires me to re-authenticate for every push which is not very nice.

Also, after changing the URL to the HTTPS one, I see the Gitlab logo and an update-arrow appearing in the status bar - but only to be replaced by the question mark and the hover comment "no Gitlabproject detected" after a second or so. I don't see any output in the console.

**Comment by blakawk** [comment]
@simonspa enable package's debug output in package's options and post the resulting console output. Also, you can have a different origin for fetch and push in git, see https://git-scm.com/docs/git-remote#git-remote-emset-urlem.

**Comment by dhope0000** [comment]
There is stack over flow question that has the answer on how to store git
credentials (I two hated authenticating every time I called the remote)

**Comment by simonspa** [comment]
This is the output:
```
[gitlab-integration] --- handle repository
[gitlab-integration]      - project: Directory
[gitlab-integration]      - repos: Directory
[gitlab-integration]      - current: undefined
[gitlab-integration]      - origin: https://gitlab.myserver.com/myuser/myproject.git
[gitlab-integration]      - url: Object
[gitlab-integration]      - name: myuser/myproject
[gitlab-integration] project myuser/myproject loading with status 'loading project...'
[gitlab-integration]  -> fetch 'projects?membership=yes' from 'gitlab.myserver.com'
[gitlab-integration] current project becomes undefined
[gitlab-integration]  <-  Response
[gitlab-integration] received projects from gitlab.myserver.com Array[20]
[gitlab-integration] project myuser/myproject is unknown
[gitlab-integration] -- path change
[gitlab-integration]     - current: undefined
[gitlab-integration]     - new: /home/myuser/software/myproject
[gitlab-integration]     - projects: Object
[gitlab-integration]     - current path: /home/myuser/software/myproject/src/modules/GenericPropagation/GenericPropagationModule.hpp
[gitlab-integration]      -> project changed to myuser/myproject
[gitlab-integration] current project becomes myuser/myproject
[gitlab-integration] project myuser/myproject is unknown
```

**Comment by blakawk** [comment]
@simonspa you have more than 20 projects defined on your gitlab ? Currently, `gitlab-integration` do not support paging in the API...

**Comment by simonspa** [comment]
@blakawk the "personal projects" page lists 14 projects only, in addition, 7 projects with contributions, but since I'm in a few groups, there are more than 20 projects I have access to. Not sure which ones do count for the API

**Comment by blakawk** [comment]
@simonspa I created #11 to implement gitlab paging API support. In the meantime, regarding this issue, I consider it as fixed. Do not hesitate to reopen/comment on it in case there is other issues.

**Comment by simonspa** [comment]
Great, thanks a lot!

**Comment by blakawk** [comment]
@simonspa here you go: https://github.com/blakawk/gitlab-integration/releases/tag/v0.4.0

**Comment by simonspa** [comment]
Thank you, that was really quick! Now it finds the project correctly, but somehow the remote hangs up when querying pipelines:

```
[gitlab-integration] project myuser/myproject loading with status 'loading project...'
[gitlab-integration]  <-  Response
[gitlab-integration]  -> retrieving 4 pages
[gitlab-integration]  -> page 2
[gitlab-integration]  -> page 3
[gitlab-integration]  -> page 4
[gitlab-integration]      <- page 2 Response_abort: false_bytes: 29228_raw: Array[2]body: PassThroughbodyUsed: trueheaders: Headersok: truesize: 0status: 200statusText: "OK"timeout: 0url: "https://gitlab.myserver.com/api/v4/projects?membership=yes&per_page=20&page=2"__proto__: Body
[gitlab-integration]      <- page 3 Response
[gitlab-integration]      <- page 4 Response
[gitlab-integration] received projects from gitlab.myserver.com Array[66]
[gitlab-integration] project myuser/myproject loading with status 'loading pipelines...'
[gitlab-integration]  -> fetch 'projects/14102/pipelines' from 'gitlab.myserver.com
cannot fetch pipelines for project myuser/myproject
FetchError
code: "ECONNRESET"
errno: "ECONNRESET"
message: "request to https://gitlab.myserver.com/api/v4/projects/14102/pipelines failed, reason: socket hang up"
name: "FetchError"
stack: (...)
get stack: stack()
set stack: stack()
type: "system"
__proto__: Error(anonymous function) @ gitlab.coffee:111
[gitlab-integration] project [object Object] update end
```

**Comment by blakawk** [comment]
@simonspa it does not retry after a while ?

**Comment by simonspa** [comment]
Ha, it does, seems like I was too impatient...
![image](https://user-images.githubusercontent.com/1677436/29041558-9afc0f46-7bb3-11e7-89bf-10adc202de34.png)
Thank you so much! :)

**Comment by blakawk** [comment]
@simonspa glad I could help 😋
